table DimPlayers
	lineageTag: 4cc27823-495c-4ca7-8d49-c8b8da14a4c7

	column PlayerID
		dataType: int64
		formatString: 0
		lineageTag: 5d07aa07-b1c7-48c2-8c01-ab2735c8fdf1
		summarizeBy: none
		sourceColumn: PlayerID

		annotation SummarizationSetBy = Automatic

	column PlayerName
		dataType: string
		lineageTag: 5955b7c6-bd48-4bd8-94a1-fba63fb84a7e
		summarizeBy: none
		sourceColumn: PlayerName

		annotation SummarizationSetBy = Automatic

	column Position
		dataType: string
		lineageTag: cda93fa8-6456-43e1-a957-185dfd89bbb4
		summarizeBy: none
		sourceColumn: Position

		annotation SummarizationSetBy = Automatic

	column ShootsCatches
		dataType: string
		lineageTag: 47428503-f2a1-46e5-b69d-8ae344c5fa0b
		summarizeBy: none
		sourceColumn: ShootsCatches

		annotation SummarizationSetBy = Automatic

	column HeadshotURL
		dataType: string
		lineageTag: 792ca273-8775-4a92-ae14-157d06865719
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: HeadshotURL

		annotation SummarizationSetBy = Automatic

	column GamesPlayed
		dataType: int64
		formatString: 0
		lineageTag: 70c59582-d7e6-4039-b4ca-07fb02dcc90b
		summarizeBy: sum
		sourceColumn: GamesPlayed

		annotation SummarizationSetBy = Automatic

	column Goals
		dataType: int64
		formatString: 0
		lineageTag: 3ff463b9-8717-4979-82cd-6a51e48d61cd
		summarizeBy: sum
		sourceColumn: Goals

		annotation SummarizationSetBy = Automatic

	column Assists
		dataType: int64
		formatString: 0
		lineageTag: 986b1221-dbb1-4de7-939e-6f633d14a7e5
		summarizeBy: sum
		sourceColumn: Assists

		annotation SummarizationSetBy = Automatic

	column Points
		dataType: int64
		formatString: 0
		lineageTag: 3b454804-acd6-4a25-8d14-eed0b902d225
		summarizeBy: sum
		sourceColumn: Points

		annotation SummarizationSetBy = Automatic

	partition DimPlayers = m
		mode: import
		source = ```
				let
				    // 1. Static Base URL and RelativePath configuration
				    BaseUrl = "https://api.nhle.com",
				    Path = "stats/rest/en/skater/summary",
				    
				    // 2. API Governance: Pull active skaters for the current 2025-2026 season
				    QueryParams = [
				        limit = "-1",
				        cayenneExp = "seasonId=20252026"
				    ],
				
				    // 3. Error Resilience: Fetch JSON
				    Source = try Json.Document(Web.Contents(BaseUrl, [RelativePath=Path, Query=QueryParams])) otherwise null,
				    DataList = try Source[data] otherwise {},
				    PlayersTable = Table.FromList(DataList, Splitter.SplitByNothing(), {"Column1"}, null, ExtraValues.Error),
				    
				    // THE UPGRADE: We are now extracting GamesPlayed, Goals, Assists, and Points directly from the NHL API
				    ExpandedPlayers = try Table.ExpandRecordColumn(PlayersTable, "Column1", 
				        {"playerId", "skaterFullName", "positionCode", "shootsCatches", "gamesPlayed", "goals", "assists", "points"}, 
				        {"PlayerID", "PlayerName", "Position", "ShootsCatches", "GamesPlayed", "Goals", "Assists", "Points"}
				    ) otherwise PlayersTable,
				
				    // Synthesize the Headshot URL 
				    AddHeadshotURL = Table.AddColumn(ExpandedPlayers, "HeadshotURL", 
				        each "https://assets.nhle.com/mugs/nhl/latest/ext/light/" & Text.From([PlayerID]) & ".png", type text),
				
				    // Memory Efficiency & Deduplication
				    FinalColumns = Table.SelectColumns(AddHeadshotURL, {"PlayerID", "PlayerName", "Position", "ShootsCatches", "GamesPlayed", "Goals", "Assists", "Points", "HeadshotURL"}, MissingField.Ignore),
				    RemoveDuplicates = Table.Distinct(FinalColumns, {"PlayerID"}),
				
				    // Data Typing
				    TypedData = Table.TransformColumnTypes(RemoveDuplicates, {
				        {"PlayerID", Int64.Type}, 
				        {"PlayerName", type text}, 
				        {"Position", type text}, 
				        {"ShootsCatches", type text},
				        {"GamesPlayed", Int64.Type},
				        {"Goals", Int64.Type},
				        {"Assists", Int64.Type},
				        {"Points", Int64.Type},
				        {"HeadshotURL", type text}
				    })
				in
				    TypedData
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

