table DimTeams
	lineageTag: 755959a4-88c2-42c4-aede-3839de96911d

	column TeamID
		dataType: int64
		formatString: 0
		lineageTag: 19320d38-c2b9-457d-80d4-1a1c7fba273a
		summarizeBy: none
		sourceColumn: TeamID

		annotation SummarizationSetBy = Automatic

	column FranchiseID
		dataType: int64
		formatString: 0
		lineageTag: 95969f73-9e20-4df9-be9a-b96cbfe4e950
		summarizeBy: none
		sourceColumn: FranchiseID

		annotation SummarizationSetBy = Automatic

	column TeamName
		dataType: string
		lineageTag: 1e174192-8cc4-4404-a942-a0d7fb2da7d2
		summarizeBy: none
		sourceColumn: TeamName

		annotation SummarizationSetBy = Automatic

	column TeamAbbrev
		dataType: string
		lineageTag: f408a944-de41-4a0b-bba5-baa93424b452
		summarizeBy: none
		sourceColumn: TeamAbbrev

		annotation SummarizationSetBy = Automatic

	column TeamLogoURL
		dataType: string
		lineageTag: 5b3257d3-68e4-4672-85b3-43f9d3e0793e
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: TeamLogoURL

		annotation SummarizationSetBy = Automatic

	column Conference
		dataType: string
		lineageTag: 20aac74a-34ad-486c-897a-7f5e76cfcb1e
		summarizeBy: none
		sourceColumn: Conference

		annotation SummarizationSetBy = Automatic

	column Division
		dataType: string
		lineageTag: edb3c2d6-8ba1-4bac-8e90-f607d1ad653c
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column LeagueRank
		dataType: int64
		formatString: 0
		lineageTag: 0c749489-1516-4081-a033-1e36e22b2657
		summarizeBy: none
		sourceColumn: LeagueRank

		annotation SummarizationSetBy = Automatic

	column Points
		dataType: int64
		formatString: 0
		lineageTag: 88df7391-7ef5-4810-ab1a-a3ba296aec85
		summarizeBy: none
		sourceColumn: Points

		annotation SummarizationSetBy = Automatic

	column StreakType
		dataType: string
		lineageTag: 4d28175b-c56a-47af-a6b4-eb65d6ec2a58
		summarizeBy: none
		sourceColumn: StreakType

		annotation SummarizationSetBy = Automatic

	column StreakCount
		dataType: int64
		formatString: 0
		lineageTag: 12c8623c-ff9b-44af-a885-10e9c6345ea5
		summarizeBy: none
		sourceColumn: StreakCount

		annotation SummarizationSetBy = Automatic

	column GoalDifferential
		dataType: int64
		formatString: 0
		lineageTag: d8617501-88e8-41be-b225-e104440564a0
		summarizeBy: none
		sourceColumn: GoalDifferential

		annotation SummarizationSetBy = Automatic

	partition DimTeams = m
		mode: import
		source = ```
				let
				    // --- 1. CORE TEAM IDs (Required for mapping Kaggle historical IDs) ---
				    CoreUrl = "https://api.nhle.com",
				    CorePath = "stats/rest/en/team",
				    CoreParams = [limit = "-1"],
				    CoreSource = try Json.Document(Web.Contents(CoreUrl, [RelativePath=CorePath, Query=CoreParams])) otherwise null,
				    CoreList = try CoreSource[data] otherwise {},
				    CoreTable = Table.FromList(CoreList, Splitter.SplitByNothing(), {"Column1"}, null, ExtraValues.Error),
				    ExpandedCore = try Table.ExpandRecordColumn(CoreTable, "Column1", 
				        {"id", "franchiseId", "fullName", "triCode"}, 
				        {"TeamID", "FranchiseID", "TeamName", "TeamAbbrev"}
				    ) otherwise CoreTable,
				    
				    // --- 2. RICH STANDINGS DATA (Live Conference, Division, Rank, Streaks) ---
				    StandUrl = "https://api-web.nhle.com",
				    StandPath = "v1/standings/now",
				    StandSource = try Json.Document(Web.Contents(StandUrl, [RelativePath=StandPath])) otherwise null,
				    StandList = try StandSource[standings] otherwise {},
				    StandTable = Table.FromList(StandList, Splitter.SplitByNothing(), {"Column1"}, null, ExtraValues.Error),
				    
				    ExpandedStandings = try Table.ExpandRecordColumn(StandTable, "Column1", 
				        {"teamAbbrev", "conferenceName", "divisionName", "leagueSequence", "points", "streakCode", "streakCount", "goalDifferential"}, 
				        {"teamAbbrevRec", "Conference", "Division", "LeagueRank", "Points", "StreakType", "StreakCount", "GoalDifferential"}
				    ) otherwise StandTable,
				    
				    // Extract the text abbreviation from the nested record {"default": "BOS"}
				    ExtractStandingsAbbrev = try Table.ExpandRecordColumn(ExpandedStandings, "teamAbbrevRec", {"default"}, {"TeamAbbrev"}) otherwise ExpandedStandings,
				    
				    // --- 3. THE MERGE (Stitching the two APIs together) ---
				    // LeftOuter Join ensures defunct/relocated teams still exist for historical game mapping
				    MergedTeams = Table.NestedJoin(ExpandedCore, {"TeamAbbrev"}, ExtractStandingsAbbrev, {"TeamAbbrev"}, "StandingsData", JoinKind.LeftOuter),
				    ExpandedMerge = Table.ExpandTableColumn(MergedTeams, "StandingsData", 
				        {"Conference", "Division", "LeagueRank", "Points", "StreakType", "StreakCount", "GoalDifferential"}, 
				        {"Conference", "Division", "LeagueRank", "Points", "StreakType", "StreakCount", "GoalDifferential"}
				    ),
				
				    // --- 4. DATA ENHANCEMENT & TYPING ---
				    // Synthesize the official NHL SVG Logo URL
				    AddLogoURL = Table.AddColumn(ExpandedMerge, "TeamLogoURL", 
				        each "https://assets.nhle.com/logos/nhl/svg/" & [TeamAbbrev] & "_light.svg", 
				        type text
				    ),
				    
				    // Cast for optimal DAX engine performance
				    TypedData = Table.TransformColumnTypes(AddLogoURL, {
				        {"TeamID", Int64.Type}, 
				        {"FranchiseID", Int64.Type}, 
				        {"TeamName", type text}, 
				        {"TeamAbbrev", type text},
				        {"Conference", type text},
				        {"Division", type text},
				        {"LeagueRank", Int64.Type},
				        {"Points", Int64.Type},
				        {"StreakType", type text},
				        {"StreakCount", Int64.Type},
				        {"GoalDifferential", Int64.Type},
				        {"TeamLogoURL", type text}
				    }),
				
				    // --- THE FIX: ENFORCE UNIQUE ABBREVIATIONS ---
				    // The NHL stats API returns legacy duplicates for some abbreviations.
				    // We must remove duplicates so this column can act as a 1-side key in the Star Schema.
				    RemovedDuplicates = Table.Distinct(TypedData, {"TeamAbbrev"})
				in
				    RemovedDuplicates
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

