table FactPlayByPlay
	lineageTag: d0614fb1-16a1-4409-80b3-445d64a7efb1

	column GameID
		dataType: string
		lineageTag: ec0f0b51-61e7-4888-b18e-b0e54d4c8489
		summarizeBy: none
		sourceColumn: GameID

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: int64
		formatString: 0
		lineageTag: e20105a4-ce30-4d36-95c2-33459f8d0465
		summarizeBy: sum
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column GameType
		dataType: int64
		formatString: 0
		lineageTag: 84784a39-09fd-41ed-8f44-ac6fb12e141f
		summarizeBy: sum
		sourceColumn: GameType

		annotation SummarizationSetBy = Automatic

	column GameDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: e60f181b-939f-4253-a2c6-7a537af8f480
		summarizeBy: none
		sourceColumn: GameDate

		variation Variation
			isDefault
			relationship: e6524962-b0ba-4ddf-b5c5-3104621cebe2
			defaultHierarchy: LocalDateTable_885770e6-6cbe-4c01-a904-6cd49b89f63e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PeriodNumber
		dataType: int64
		formatString: 0
		lineageTag: 718de994-ad28-4d42-a466-e65911895fda
		summarizeBy: sum
		sourceColumn: PeriodNumber

		annotation SummarizationSetBy = Automatic

	column TimeRemaining
		dataType: string
		lineageTag: ece713fa-d14b-4feb-b35f-7b608fd56df2
		summarizeBy: none
		sourceColumn: TimeRemaining

		annotation SummarizationSetBy = Automatic

	column EventID
		dataType: string
		lineageTag: 20b4e09e-4b8b-4caf-934d-272a0c64c3c8
		summarizeBy: none
		sourceColumn: EventID

		annotation SummarizationSetBy = Automatic

	column 'PeriodNumber.1'
		dataType: string
		lineageTag: f86fee30-8a71-455c-9981-e84e4facc1af
		summarizeBy: none
		sourceColumn: PeriodNumber.1

		annotation SummarizationSetBy = Automatic

	column TimeInPeriod_Seconds
		dataType: string
		lineageTag: 43793c61-9333-4a3a-a017-0cf9a7e87a89
		summarizeBy: none
		sourceColumn: TimeInPeriod_Seconds

		annotation SummarizationSetBy = Automatic

	column EventType
		dataType: string
		lineageTag: 4b57095e-1732-4ecf-8fce-972f01ae7696
		summarizeBy: none
		sourceColumn: EventType

		annotation SummarizationSetBy = Automatic

	column EventTeamID
		dataType: string
		lineageTag: f62325bd-01cd-4693-b781-a1e91ac08b21
		summarizeBy: none
		sourceColumn: EventTeamID

		annotation SummarizationSetBy = Automatic

	column X_Coord
		dataType: string
		lineageTag: e685cfc2-ef52-490b-b663-44441787a7cc
		summarizeBy: none
		sourceColumn: X_Coord

		annotation SummarizationSetBy = Automatic

	column Y_Coord
		dataType: string
		lineageTag: 23f52815-8963-4b68-b998-b4fa039bc996
		summarizeBy: none
		sourceColumn: Y_Coord

		annotation SummarizationSetBy = Automatic

	column ScoringPlayerID
		dataType: string
		lineageTag: 35e1d17b-b7ae-4673-a74c-d8796f50aa9d
		summarizeBy: none
		sourceColumn: ScoringPlayerID

		annotation SummarizationSetBy = Automatic

	column ShootingPlayerID
		dataType: string
		lineageTag: a0657267-5dde-4e7d-af88-bef6ef4f7c62
		summarizeBy: none
		sourceColumn: ShootingPlayerID

		annotation SummarizationSetBy = Automatic

	column HittingPlayerID
		dataType: string
		lineageTag: fe796bfb-05de-4ec5-853f-d72f392afe75
		summarizeBy: none
		sourceColumn: HittingPlayerID

		annotation SummarizationSetBy = Automatic

	column HitteePlayerID
		dataType: string
		lineageTag: b0d7c320-38df-4b5b-9513-18fa65474036
		summarizeBy: none
		sourceColumn: HitteePlayerID

		annotation SummarizationSetBy = Automatic

	partition FactPlayByPlay = m
		mode: import
		source =
				let
				    Source = DimGameTracker,
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"GameID", type text}}),
				    #"Invoked Custom Function" = Table.AddColumn(#"Changed Type", "fxGetPlayByPlay", each fxGetPlayByPlay([GameID])),
				    #"Expanded fxGetPlayByPlay" = Table.ExpandTableColumn(#"Invoked Custom Function", "fxGetPlayByPlay", {"EventID", "PeriodNumber", "TimeInPeriod_Seconds", "EventType", "EventTeamID", "X_Coord", "Y_Coord", "ScoringPlayerID", "ShootingPlayerID", "HittingPlayerID", "HitteePlayerID"}, {"EventID", "PeriodNumber.1", "TimeInPeriod_Seconds", "EventType", "EventTeamID", "X_Coord", "Y_Coord", "ScoringPlayerID", "ShootingPlayerID", "HittingPlayerID", "HitteePlayerID"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Expanded fxGetPlayByPlay",{"GameState", "HomeTeamID", "HomeTeamAbbrev", "HomeScore", "AwayTeamID", "AwayTeamAbbrev", "AwayScore"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

