table FactEdgeBurstDetails
	lineageTag: f9823446-ee09-40ee-b8b8-b67bfae7fe60

	column PlayerID
		dataType: int64
		lineageTag: 63f51f3f-9c5e-4cd6-b4a1-3c722ac0a760
		sourceColumn: PlayerID

	column 'SkatingSpeedDetails.maxSkatingSpeed.imperial'
		dataType: double
		lineageTag: 0b1d0e6c-d515-429c-a615-ccf6687f9434
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.imperial

	column 'SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.imperial'
		dataType: double
		lineageTag: 0339ea95-458c-41b7-bca3-a1f743038bd9
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.imperial

	column burstsOver22
		dataType: int64
		formatString: 0
		lineageTag: 530e7c9d-d1ab-4387-b5fa-e27ccf98ff79
		summarizeBy: sum
		sourceColumn: burstsOver22

		annotation SummarizationSetBy = Automatic

	column bursts20To22
		dataType: int64
		formatString: 0
		lineageTag: fdf09fbc-3208-48c6-a7bf-8d42b6bccef4
		summarizeBy: sum
		sourceColumn: bursts20To22

		annotation SummarizationSetBy = Automatic

	column bursts18To20
		dataType: int64
		formatString: 0
		lineageTag: dad6a708-8c4a-4918-9d27-a3910b50e756
		summarizeBy: sum
		sourceColumn: bursts18To20

		annotation SummarizationSetBy = Automatic

	partition FactEdgeBurstDetails = m
		mode: import
		source =
				let
				    Source = Staging_EDGE,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"TopSkatingSpeeds"}),
				
				    // Force the expansion of ALL nested fields
				    #"Expanded" = Table.ExpandRecordColumn(#"Removed Columns", "SkatingSpeedDetails", {"maxSkatingSpeed", "burstsOver22", "bursts20To22", "bursts18To20"}),
				
				    // SURGICAL EXTRACTION: Use a safer method to grab only the 'count' value if it's a record
				    GetCount = (val) => if val is record then try val[count] otherwise 0 else val,
				
				    AddOver22 = Table.TransformColumns(#"Expanded", {{"burstsOver22", each GetCount(_)}}),
				    Add20To22 = Table.TransformColumns(AddOver22, {{"bursts20To22", each GetCount(_)}}),
				    Add18To20 = Table.TransformColumns(Add20To22, {{"bursts18To20", each GetCount(_)}}),
				
				    // Handle Speeds
				    #"ExpandedMax" = Table.ExpandRecordColumn(Add18To20, "maxSkatingSpeed", {"imperial", "leagueAvg"}),
				    #"ExpandedAvg" = Table.ExpandRecordColumn(#"ExpandedMax", "leagueAvg", {"imperial"}, {"avg.imp"}),
				
				    // Final Strict Typing
				    Typed = Table.TransformColumnTypes(#"ExpandedAvg", {
				        {"PlayerID", Int64.Type},
				        {"imperial", type number},
				        {"avg.imp", type number},
				        {"burstsOver22", Int64.Type},
				        {"bursts20To22", Int64.Type},
				        {"bursts18To20", Int64.Type}
				    }),
				
				    FinalRenamed = Table.RenameColumns(Typed, {
				        {"imperial", "SkatingSpeedDetails.maxSkatingSpeed.imperial"},
				        {"avg.imp", "SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.imperial"}
				    })
				in
				    FinalRenamed

