table FactEdgeBurstDetails
	lineageTag: f9823446-ee09-40ee-b8b8-b67bfae7fe60

	column PlayerID
		dataType: string
		lineageTag: f34a2b91-59f0-4070-a16a-b904c44568b2
		summarizeBy: none
		sourceColumn: PlayerID

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.imperial'
		dataType: string
		lineageTag: d86f4245-dc53-4607-a380-3e453826caab
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.imperial

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.metric'
		dataType: string
		lineageTag: 2669ea18-3b3e-4fb7-a238-d0b39cbf7600
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.metric

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.percentile'
		dataType: string
		lineageTag: 577ced23-edc1-450e-ab30-d7e06d38b0e2
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.percentile

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.imperial'
		dataType: string
		lineageTag: bcbd76e8-3186-4d6c-bfe8-d5746fbd65e1
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.imperial

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.metric'
		dataType: string
		lineageTag: 0332ad78-318b-453e-957f-273da4cc1a98
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.metric

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.player.firstName.default'
		dataType: string
		lineageTag: 2cf4d853-8d42-43fe-a1c6-1a2d031fa9bc
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.player.firstName.default

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.player.lastName'
		dataType: string
		lineageTag: 45ee8306-16ef-4b5b-9a4d-a545051f1925
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.player.lastName

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.gameDate'
		dataType: string
		lineageTag: f3330b11-5e93-4959-9090-9d83fc843ae6
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.gameDate

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.awayTeam'
		dataType: string
		lineageTag: 0f65d272-2f83-4de9-907b-0cda2bed97e8
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.awayTeam

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.homeTeam'
		dataType: string
		lineageTag: d9e38a73-f074-4358-8ae4-f8299aa84d49
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.homeTeam

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.gameOutcome'
		dataType: string
		lineageTag: 14827254-11bd-4a26-9059-c50207fed10f
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.gameOutcome

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.periodDescriptor'
		dataType: string
		lineageTag: 7a25119b-8e4b-440c-832b-98eb2f703250
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.periodDescriptor

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.timeInPeriod'
		dataType: string
		lineageTag: 4294ca64-6d57-464e-ad07-f4981518b343
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.timeInPeriod

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.maxSkatingSpeed.overlay.gameType'
		dataType: string
		lineageTag: 7232e105-21bd-4d69-b3e5-2fc9da4b6f1b
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.maxSkatingSpeed.overlay.gameType

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.burstsOver22'
		dataType: string
		lineageTag: 93ac8c46-7ce4-4472-ad43-722961846dfe
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.burstsOver22

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.bursts20To22'
		dataType: string
		lineageTag: 2d51fe06-fcd3-412f-9afd-c37fe0a278f5
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.bursts20To22

		annotation SummarizationSetBy = Automatic

	column 'SkatingSpeedDetails.bursts18To20'
		dataType: string
		lineageTag: 615b43b0-a5d2-451b-9aff-ea52509f615e
		summarizeBy: none
		sourceColumn: SkatingSpeedDetails.bursts18To20

		annotation SummarizationSetBy = Automatic

	partition FactEdgeBurstDetails = m
		mode: import
		source =
				let
				    Source = Staging_EDGE,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"TopSkatingSpeeds"}),
				    #"Expanded SkatingSpeedDetails" = Table.ExpandRecordColumn(#"Removed Columns", "SkatingSpeedDetails", {"maxSkatingSpeed", "burstsOver22", "bursts20To22", "bursts18To20"}, {"SkatingSpeedDetails.maxSkatingSpeed", "SkatingSpeedDetails.burstsOver22", "SkatingSpeedDetails.bursts20To22", "SkatingSpeedDetails.bursts18To20"}),
				    #"Expanded SkatingSpeedDetails.maxSkatingSpeed" = Table.ExpandRecordColumn(#"Expanded SkatingSpeedDetails", "SkatingSpeedDetails.maxSkatingSpeed", {"imperial", "metric", "percentile", "leagueAvg", "overlay"}, {"SkatingSpeedDetails.maxSkatingSpeed.imperial", "SkatingSpeedDetails.maxSkatingSpeed.metric", "SkatingSpeedDetails.maxSkatingSpeed.percentile", "SkatingSpeedDetails.maxSkatingSpeed.leagueAvg", "SkatingSpeedDetails.maxSkatingSpeed.overlay"}),
				    #"Expanded SkatingSpeedDetails.maxSkatingSpeed.overlay" = Table.ExpandRecordColumn(#"Expanded SkatingSpeedDetails.maxSkatingSpeed", "SkatingSpeedDetails.maxSkatingSpeed.overlay", {"player", "gameDate", "awayTeam", "homeTeam", "gameOutcome", "periodDescriptor", "timeInPeriod", "gameType"}, {"SkatingSpeedDetails.maxSkatingSpeed.overlay.player", "SkatingSpeedDetails.maxSkatingSpeed.overlay.gameDate", "SkatingSpeedDetails.maxSkatingSpeed.overlay.awayTeam", "SkatingSpeedDetails.maxSkatingSpeed.overlay.homeTeam", "SkatingSpeedDetails.maxSkatingSpeed.overlay.gameOutcome", "SkatingSpeedDetails.maxSkatingSpeed.overlay.periodDescriptor", "SkatingSpeedDetails.maxSkatingSpeed.overlay.timeInPeriod", "SkatingSpeedDetails.maxSkatingSpeed.overlay.gameType"}),
				    #"Expanded SkatingSpeedDetails.maxSkatingSpeed.overlay.player" = Table.ExpandRecordColumn(#"Expanded SkatingSpeedDetails.maxSkatingSpeed.overlay", "SkatingSpeedDetails.maxSkatingSpeed.overlay.player", {"firstName", "lastName"}, {"SkatingSpeedDetails.maxSkatingSpeed.overlay.player.firstName", "SkatingSpeedDetails.maxSkatingSpeed.overlay.player.lastName"}),
				    #"Expanded SkatingSpeedDetails.maxSkatingSpeed.overlay.player.firstName" = Table.ExpandRecordColumn(#"Expanded SkatingSpeedDetails.maxSkatingSpeed.overlay.player", "SkatingSpeedDetails.maxSkatingSpeed.overlay.player.firstName", {"default"}, {"SkatingSpeedDetails.maxSkatingSpeed.overlay.player.firstName.default"}),
				    #"Expanded SkatingSpeedDetails.maxSkatingSpeed.leagueAvg" = Table.ExpandRecordColumn(#"Expanded SkatingSpeedDetails.maxSkatingSpeed.overlay.player.firstName", "SkatingSpeedDetails.maxSkatingSpeed.leagueAvg", {"imperial", "metric"}, {"SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.imperial", "SkatingSpeedDetails.maxSkatingSpeed.leagueAvg.metric"})
				in
				    #"Expanded SkatingSpeedDetails.maxSkatingSpeed.leagueAvg"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

