table FactPlayByPlay
	lineageTag: d0614fb1-16a1-4409-80b3-445d64a7efb1

	column GameID
		dataType: int64
		formatString: 0
		lineageTag: ec0f0b51-61e7-4888-b18e-b0e54d4c8489
		summarizeBy: count
		sourceColumn: GameID

		annotation SummarizationSetBy = Automatic

	column PeriodNumber
		dataType: int64
		formatString: 0
		lineageTag: 718de994-ad28-4d42-a466-e65911895fda
		summarizeBy: sum
		sourceColumn: PeriodNumber

		annotation SummarizationSetBy = Automatic

	column EventID
		dataType: string
		lineageTag: 20b4e09e-4b8b-4caf-934d-272a0c64c3c8
		summarizeBy: none
		sourceColumn: EventID

		annotation SummarizationSetBy = Automatic

	column TimeInPeriod_Seconds
		dataType: int64
		formatString: 0
		lineageTag: 43793c61-9333-4a3a-a017-0cf9a7e87a89
		summarizeBy: sum
		sourceColumn: TimeInPeriod_Seconds

		annotation SummarizationSetBy = Automatic

	column EventType
		dataType: string
		lineageTag: 4b57095e-1732-4ecf-8fce-972f01ae7696
		summarizeBy: none
		sourceColumn: EventType

		annotation SummarizationSetBy = Automatic

	column EventTeamID
		dataType: int64
		formatString: 0
		lineageTag: f62325bd-01cd-4693-b781-a1e91ac08b21
		summarizeBy: none
		sourceColumn: EventTeamID

		annotation SummarizationSetBy = Automatic

	column X_Coord
		dataType: double
		lineageTag: e685cfc2-ef52-490b-b663-44441787a7cc
		summarizeBy: sum
		sourceColumn: X_Coord

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Y_Coord
		dataType: double
		lineageTag: 23f52815-8963-4b68-b998-b4fa039bc996
		summarizeBy: sum
		sourceColumn: Y_Coord

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ScoringPlayerID
		dataType: int64
		formatString: 0
		lineageTag: 35e1d17b-b7ae-4673-a74c-d8796f50aa9d
		summarizeBy: count
		sourceColumn: ScoringPlayerID

		annotation SummarizationSetBy = Automatic

	column ShootingPlayerID
		dataType: int64
		formatString: 0
		lineageTag: a0657267-5dde-4e7d-af88-bef6ef4f7c62
		summarizeBy: none
		sourceColumn: ShootingPlayerID

		annotation SummarizationSetBy = Automatic

	column HittingPlayerID
		dataType: int64
		formatString: 0
		lineageTag: fe796bfb-05de-4ec5-853f-d72f392afe75
		summarizeBy: count
		sourceColumn: HittingPlayerID

		annotation SummarizationSetBy = Automatic

	column HitteePlayerID
		dataType: int64
		formatString: 0
		lineageTag: b0d7c320-38df-4b5b-9513-18fa65474036
		summarizeBy: count
		sourceColumn: HitteePlayerID

		annotation SummarizationSetBy = Automatic

	partition FactPlayByPlay = m
		mode: import
		source = ```
				let
				    // --- BRANCH A: LIVE API DATA ---
				    SourceTracker = DimGameTracker,
				    
				    // Keep ONLY the GameID before invoking the function
				    IsolatedGameID = Table.SelectColumns(SourceTracker, {"GameID"}),
				    ChangedTypeStr = Table.TransformColumnTypes(IsolatedGameID, {{"GameID", type text}}),
				    
				    // Invoke the live play-by-play API
				    InvokedAPI = Table.AddColumn(ChangedTypeStr, "LivePlays", each fxGetPlayByPlay([GameID])),
				    
				    // Expand the live play results cleanly
				    ExpandedLivePlays = Table.ExpandTableColumn(InvokedAPI, "LivePlays", 
				        {"EventID", "PeriodNumber", "TimeInPeriod_Seconds", "EventType", "EventTeamID", "X_Coord", "Y_Coord", "ScoringPlayerID", "ShootingPlayerID", "HittingPlayerID", "HitteePlayerID"}, 
				        {"EventID", "PeriodNumber", "TimeInPeriod_Seconds", "EventType", "EventTeamID", "X_Coord", "Y_Coord", "ScoringPlayerID", "ShootingPlayerID", "HittingPlayerID", "HitteePlayerID"}
				    ),
				
				    // Ensure live API text fields are clean before append
				    CleanedLive = Table.TransformColumnTypes(ExpandedLivePlays, {{"EventID", type text}, {"EventTeamID", type text}}),
				
				    // --- THE UNION ---
				    // Stack the Live API data on top of the Kaggle CSV history
				    AppendedData = try Table.Combine({CleanedLive, Staging_HistoricalPlays}) otherwise CleanedLive,
				
				    // --- FINAL DATA TYPING FOR STAR SCHEMA ---
				    // Safely cast everything to Whole Numbers EXCEPT EventID, which must remain text due to Kaggle's formatting
				    TypedData = Table.TransformColumnTypes(AppendedData, {
				        {"GameID", Int64.Type},
				        {"EventID", type text},               // <-- FIX: Kept as text to prevent composite string errors
				        {"PeriodNumber", Int64.Type},
				        {"TimeInPeriod_Seconds", Int64.Type},
				        {"EventType", type text},
				        {"EventTeamID", Int64.Type},          // <-- Safe to cast now that "NA"s are gone
				        {"X_Coord", type number},
				        {"Y_Coord", type number},
				        {"ScoringPlayerID", Int64.Type},
				        {"ShootingPlayerID", Int64.Type},
				        {"HittingPlayerID", Int64.Type},
				        {"HitteePlayerID", Int64.Type}
				    })
				in
				    TypedData
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

