table FactLivePlays
	isHidden
	lineageTag: d0614fb1-16a1-4409-80b3-445d64a7efb1

	column GameID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ec0f0b51-61e7-4888-b18e-b0e54d4c8489
		summarizeBy: count
		sourceColumn: GameID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PeriodNumber
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 718de994-ad28-4d42-a466-e65911895fda
		summarizeBy: sum
		sourceColumn: PeriodNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EventID
		dataType: string
		isHidden
		lineageTag: 20b4e09e-4b8b-4caf-934d-272a0c64c3c8
		summarizeBy: none
		sourceColumn: EventID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TimeInPeriod_Seconds
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 43793c61-9333-4a3a-a017-0cf9a7e87a89
		summarizeBy: sum
		sourceColumn: TimeInPeriod_Seconds

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EventType
		dataType: string
		isHidden
		lineageTag: 4b57095e-1732-4ecf-8fce-972f01ae7696
		summarizeBy: none
		sourceColumn: EventType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column EventTeamID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f62325bd-01cd-4693-b781-a1e91ac08b21
		summarizeBy: count
		sourceColumn: EventTeamID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column X_Coord
		dataType: double
		isHidden
		lineageTag: e685cfc2-ef52-490b-b663-44441787a7cc
		summarizeBy: sum
		sourceColumn: X_Coord

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Y_Coord
		dataType: double
		isHidden
		lineageTag: 23f52815-8963-4b68-b998-b4fa039bc996
		summarizeBy: sum
		sourceColumn: Y_Coord

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ScoringPlayerID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 35e1d17b-b7ae-4673-a74c-d8796f50aa9d
		summarizeBy: count
		sourceColumn: ScoringPlayerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ShootingPlayerID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a0657267-5dde-4e7d-af88-bef6ef4f7c62
		summarizeBy: count
		sourceColumn: ShootingPlayerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HittingPlayerID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: fe796bfb-05de-4ec5-853f-d72f392afe75
		summarizeBy: count
		sourceColumn: HittingPlayerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HitteePlayerID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b0d7c320-38df-4b5b-9513-18fa65474036
		summarizeBy: count
		sourceColumn: HitteePlayerID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PlayerID
		dataType: int64
		formatString: 0
		lineageTag: 930604f6-f666-42cd-9a1a-791490ec8181
		summarizeBy: count
		sourceColumn: PlayerID

		annotation SummarizationSetBy = Automatic

	partition FactLivePlays = m
		mode: import
		source = ```
				let
				    SourceTracker = DimGames,
				    #"Filtered Rows" = Table.SelectRows(SourceTracker, each ([Season] = 20252026)),
				    
				    IsolatedGameID = Table.SelectColumns(#"Filtered Rows", {"GameID"}),
				    ChangedTypeStr = Table.TransformColumnTypes(IsolatedGameID, {{"GameID", type text}}),
				    
				    // Invoke the API for each GameID
				    InvokedAPI = Table.AddColumn(ChangedTypeStr, "LivePlays", each fxGetPlayByPlay([GameID])),
				    
				    // Expand the JSON response from the API
				    ExpandedLivePlays = Table.ExpandTableColumn(InvokedAPI, "LivePlays", 
				        {"EventID", "PeriodNumber", "TimeInPeriod_Seconds", "EventType", "EventTeamID", "X_Coord", "Y_Coord", "ScoringPlayerID", "ShootingPlayerID", "HittingPlayerID", "HitteePlayerID"}, 
				        {"EventID", "PeriodNumber", "TimeInPeriod_Seconds", "EventType", "EventTeamID", "X_Coord", "Y_Coord", "ScoringPlayerID", "ShootingPlayerID", "HittingPlayerID", "HitteePlayerID"}
				    ),
				    
				    TypedData = Table.TransformColumnTypes(ExpandedLivePlays, {
				        {"GameID", Int64.Type}, {"EventID", type text}, {"PeriodNumber", Int64.Type},
				        {"TimeInPeriod_Seconds", Int64.Type}, {"EventType", type text}, {"EventTeamID", Int64.Type},          
				        {"X_Coord", type number}, {"Y_Coord", type number}, {"ScoringPlayerID", Int64.Type},
				        {"ShootingPlayerID", Int64.Type}, {"HittingPlayerID", Int64.Type}, {"HitteePlayerID", Int64.Type}
				    }),
				    
				    #"Filtered Rows1" = Table.SelectRows(TypedData, each ([EventType] <> null and [EventType] <> "game-end" and [EventType] <> "period-end" and [EventType] <> "period-start" and [EventType] <> "shootout-complete" and [EventType] <> "stoppage")),
				
				    // THE FIX: Coalesce the specific IDs into one master PlayerID column
				    AddPlayerID = Table.AddColumn(#"Filtered Rows1", "PlayerID", each 
				        if [ScoringPlayerID] <> null then [ScoringPlayerID]
				        else if [ShootingPlayerID] <> null then [ShootingPlayerID]
				        else if [HittingPlayerID] <> null then [HittingPlayerID]
				        else if [HitteePlayerID] <> null then [HitteePlayerID]
				        else null, Int64.Type
				    ),
				
				    // Lock in the exact column order for the DAX UNION
				    FinalSchema = Table.ReorderColumns(AddPlayerID, {"GameID", "EventID", "PeriodNumber", "TimeInPeriod_Seconds", "EventType", "EventTeamID", "X_Coord", "Y_Coord", "PlayerID", "ScoringPlayerID", "ShootingPlayerID", "HittingPlayerID", "HitteePlayerID"}),
				    #"Filtered Rows2" = Table.SelectRows(FinalSchema, each ([PlayerID] <> null))
				in
				    #"Filtered Rows2"
				```

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

